[[plugins]] # 非同期処理
repo = 'Shougo/vimproc.vim'

[[plugins]]
repo = 'joshdick/onedark.vim.git'

#[[plugins]] # colorschema
#repo = 'chriskempson/vim-tomorrow-theme'

[[plugins]] # slimのハイライト
repo = 'slim-template/vim-slim'

[[plugins]] # ES6のハイライト
repo = 'othree/yajs.vim'

[[plugins]] # インデントを見やすく
repo = 'Yggdroot/indentLine'

[[plugins]] # j,kによる移動を爆速に
repo = 'rhysd/accelerated-jk'

[[plugins]] # rails
repo = 'tpope/vim-rails'

#[[plugins]]
#repo = 'ludovicchabant/vim-gutentags'
#
#[[plugins]]
#repo = 'lighttiger2505/gtags.vim'
#hook_add = '''
#    " Options
#    let g:Gtags_Auto_Map = 0
#    let g:Gtags_OpenQuickfixWindow = 1
#    " Keymap
#    " Show definetion of function cousor word on quickfix
#    nmap <silent> K :<C-u>exe("Gtags ".expand('<cword>'))<CR>
#    " Show reference of cousor word on quickfix
#    nmap <silent> R :<C-u>exe("Gtags -r ".expand('<cword>'))<CR>
#'''
#
#[[plugins]]
#repo = 'jsfaint/gen_tags.vim'
#hook_add = '''
#    let g:gen_tags#gtags_auto_gen = 1
#'''

[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = ['javascript', 'javascript.jsx']

[[plugins]]
repo = 'mxw/vim-jsx'
on_ft = ['javascript', 'javascript.jsx']

#[[plugins]]
#repo = 'moll/vim-node'
#on_ft = ['javascript']

[[plugins]]
repo = 'w0rp/ale.git'
on_source = ['lightline.vim']
hook_add = '''
  let g:ale_statusline_format = ['⨉ %d', '⚠ %d', '']
  let g:ale_echo_msg_format = '[%linter%] %s'
  nmap <silent> <C-k> <Plug>(ale_previous_wrap)
  nmap <silent> <C-j> <Plug>(ale_next_wrap)
'''

#[[plugins]]
#repo = 'dikiaap/minimalist'

[[plugins]]
repo = 'MaxMEllon/vim-jsx-pretty'

[[plugins]]
repo = 'othree/html5.vim'

[[plugins]]
repo = 'mechatroner/rainbow_csv'

[[plugins]]
repo  = 'prettier/vim-prettier'
build = 'yarn install'
